### ISSUE TITLE
Is your spikeheap/nhs-number-validator dependency officially sanctioned?

### ISSUE THREAD

**Issue by kevinkuszyk** [NHSDigital/personal-demographics-service-api#500]
Hello folks,

I see you have a dependency on [spikeheap/nhs-number-validator](https://github.com/spikeheap/nhs-number-validator) along with several other API management projects.

Has anyone your end signed off on this?  I'm considering taking a dependency on this over in Forms, but I'm wary of node packages that are maintained by one person in their spare time.

I'm also consider approaching the owner to see if he would like to donate it NHS Digital.  I would be more comfortable depending on an official implementation (and I'm sure others would too).  Do you have any thoughts / views on this?

ps. @strutt 👋

**Comment by AlexLord1** [comment]
Thanks @kevinkuszyk - we're going to take a look at this. We were not consciously aware of it in the team - so we're going to do a review of our packages, starting with this one, and we'll get back to you.

Is it it mission critical to you? i.e. if we did it in a sprint or so, would that be okay?

**Comment by kevinkuszyk** [comment]
@AlexLord1 thanks.  It looks like a few of these projects have it as it was included in the template, but it's since been removed from there.

We're working on an nhs number component for forms at the moment, and I didn't want to re-invent the wheel when it comes to validation.  With the change freeze kicking in next week, we won't be shipping it until after Christmas anyway.

Also, feel free to ping me on Slack if you want to continue this conversation in private.
